---
- name: Download uv installer
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.get_url:
    url: https://astral.sh/uv/install.sh
    dest: "{{ paperless_ngx_dependency_install_tmp_dir }}/uv-install.sh"
    mode: "0700"
  register: _uv_installer

- name: Install uv system-wide
  become: true
  ansible.builtin.command:
    cmd: "{{ paperless_ngx_dependency_install_tmp_dir }}/uv-install.sh"
    creates: /usr/local/bin/uv
  environment:
    UV_INSTALL_DIR: /usr/local/bin
    UV_NO_MODIFY_PATH: "1"
    UV_UNMANAGED_INSTALL: /usr/local/bin

- name: Remove uv installer script
  become: true
  ansible.builtin.file:
    path: "{{ paperless_ngx_dependency_install_tmp_dir }}/uv-install.sh"
    state: absent

- name: Install python via uv
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.command:
    # --upgrade will update the existing Python installation to the latest patch version.
    cmd: "uv python install {{ paperless_ngx_python_version_short }} --no-progress --color=never --upgrade"
  register: _uv_python_install
  # When uv will correctly install or update Python, it will print this line:
  # "Installed Python 3.14.7 in 946ms".
  # We can't use command return code here, since uv will return 0 in all cases.
  changed_when: '"Installed Python " in (_uv_python_install.stdout ~ _uv_python_install.stderr)'
