---
- name: Install uv
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.pip:
    name: uv
    # Install it globally
    break_system_packages: true
    state: latest

- name: Install python via uv
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.command:
    # --upgrade will update the existing Python installation to the latest patch version.
    cmd: "uv python install {{ paperless_ngx_python_version_short }} --no-progress --color=never --upgrade"
  register: _uv_python_install
  # When uv will correctly install or update Python, it will print this line:
  # "Installed Python 3.14.7 in 946ms".
  # We can't use command return code here, since uv will return 0 in all cases.
  changed_when: '"Installed Python " in (_uv_python_install.stdout ~ _uv_python_install.stderr)'
