---
- name: Check if uv is installed
  ansible.builtin.stat:
    path: /usr/local/bin/uv
  register: _uv_binary

- name: Install uv
  when: not _uv_binary.stat.exists
  block:
    - name: Download uv installer
      become: true
      become_user: "{{ paperless_ngx_system_user }}"
      ansible.builtin.get_url:
        url: https://astral.sh/uv/install.sh
        dest: "{{ paperless_ngx_dependency_install_tmp_dir }}/uv-install.sh"
        mode: "0700"
      register: _uv_installer

    - name: Install uv system-wide
      become: true
      ansible.builtin.command:
        cmd: "{{ paperless_ngx_dependency_install_tmp_dir }}/uv-install.sh"
        creates: /usr/local/bin/uv
      environment:
        # Unmanaged install means that uv won't install self updater (for `uv self update` command).
        # Also it won't change the .profile or .bashrc of the paperless-ngx user. Ansible won't read them anyway,
        # so this is a desired behavior.
        UV_UNMANAGED_INSTALL: /usr/local/bin

    - name: Remove uv installer script
      become: true
      ansible.builtin.file:
        path: "{{ paperless_ngx_dependency_install_tmp_dir }}/uv-install.sh"
        state: absent

- name: Create a folder for Python binaries
  become: true
  ansible.builtin.file:
    path: /opt/python
    owner: "{{ paperless_ngx_system_user }}"
    group: "{{ paperless_ngx_system_group }}"
    mode: "0755"
    state: directory

- name: Install python via uv
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.command:
    # --upgrade will update the existing Python installation to the latest patch version.
    cmd: "uv python install {{ paperless_ngx_python_version_short }} --no-progress --color=never --upgrade"
  environment:
    UV_PYTHON_INSTALL_DIR: "{{ paperless_ngx_dir_python }}"
  register: _uv_python_install
  # When uv will correctly install or update Python, it will print this line:
  # "Installed Python 3.14.7 in 946ms".
  # We can't use command return code here, since uv will return 0 in all cases.
  changed_when: '"Installed Python " in (_uv_python_install.stdout ~ _uv_python_install.stderr)'
