---
- name: Check virtualenv python version
  ansible.builtin.stat:
    path: "{{ paperless_ngx_dir_virtualenv }}/bin/python{{ paperless_ngx_python_version_short }}"
  register: _venv_python_bin

- name: Drop venv folder
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.file:
    # This task will remove venv folder if either we want to update Python
    # to a next major version (like, 3.13 -> 3.14). Or if venv folder doesn't exist.
    path: "{{ paperless_ngx_dir_virtualenv }}"
    state: absent
  when: not _venv_python_bin.stat.exists

- name: Set up python virtualenv
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.command:
    # --seed option also installs pip into created venv.
    cmd: uv venv --no-python-downloads --no-progress --color=never --seed
    chdir: "{{ paperless_ngx_dir_installation }}"
    creates: "{{ paperless_ngx_dir_virtualenv }}"

- name: Install paperless-ngx python requirements
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.command:
    # --strict means that uv will validate venv after this command, to check
    # if there are some packages with missing dependencies or any other problems.
    # --exact means that uv will remove any packages from venv
    # that are not mentioned in requirements.txt
    cmd: uv pip install -r requirements.txt --no-python-downloads --no-progress --color=never --strict --exact
    chdir: "{{ paperless_ngx_dir_installation }}"
  register: _uv_pip_install
  changed_when: >-
    ('Installed' in _uv_pip_install.stderr)
    or ('Uninstalled' in _uv_pip_install.stderr)

- name: Set ownership and permissions on pngx venv
  become: true
  ansible.builtin.file:
    path: "{{ paperless_ngx_dir_virtualenv }}"
    state: directory
    owner: "{{ paperless_ngx_system_user }}"
    group: "{{ paperless_ngx_system_group }}"
    mode: g-w,o-rwx
