---
- name: Check virtualenv python version
  ansible.builtin.stat:
    path: "{{ paperless_ngx_dir_virtualenv }}/bin/python{{ paperless_ngx_python_version_short }}"
  register: _venv_python_bin

- name: Drop venv folder
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.file:
    # This task will remove venv folder if either we want to update Python
    # to a next major version (like, 3.13 -> 3.14). Or if venv folder doesn't exist.
    path: "{{ paperless_ngx_dir_virtualenv }}"
    state: absent
  when: not _venv_python_bin.stat.exists

- name: Install paperless-ngx python requirements
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.command:
    cmd: >-
      uv sync --frozen --no-dev --extra postgres --extra webserver
      --python {{ paperless_ngx_python_version_short }}
      --no-python-downloads --no-progress --color=never
    chdir: "{{ paperless_ngx_dir_installation }}"
  environment:
    UV_PYTHON_INSTALL_DIR: "{{ paperless_ngx_dir_python }}"
  register: _uv_install
  changed_when: >-
    ('Installed' in _uv_install.stderr)
    or ('Uninstalled' in _uv_install.stderr)

- name: Set ownership and permissions on pngx venv
  become: true
  ansible.builtin.file:
    path: "{{ paperless_ngx_dir_virtualenv }}"
    state: directory
    owner: "{{ paperless_ngx_system_user }}"
    group: "{{ paperless_ngx_system_group }}"
    mode: g-w,o-rwx
