---
name: PR Labeling

"on":
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - unlabeled

jobs:
  # Check that conventional commit messages are used in the title of the PR
  pr_title_check:
    name: Check the PR title to be compliant with conventional commits
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Autogenerate labels based on the PR title
  pr_auto_labeling:
    name: Automatically label the PR
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    needs:
      - pr_title_check
    steps:
      - uses: release-drafter/release-drafter/autolabeler@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
        with:
          config-name: pr_autolabeling_config.yml
          token: ${{ secrets.GITHUB_TOKEN }}

  pr_label_check:
    name: Check that the PR is labeled
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    needs:
      - pr_auto_labeling
    steps:
      - uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # v5.6.0
        with:
          mode: minimum
          count: 1
          labels: |
            breaking
            bug
            build
            ci
            dependencies
            documentation
            duplicate
            enhancement
            good first issue
            help wanted
            invalid
            performance
            question
            refactoring
            removal
            style
            security
            testing
            wontfix
            skip-changelog
